//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OerProd
{
    
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ImportExportException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(APIValidationException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ImportExportCanceledException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://base.openapi.registry.flashline.com")]
    public partial class OpenAPIException
    {
        
        private string[] messageArgumentsField;
        
        private int serverErrorCodeField;
        
        private string serverMessageField;
        
        private string serverStackTraceField;
        
        private string severityField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] messageArguments
        {
            get
            {
                return this.messageArgumentsField;
            }
            set
            {
                this.messageArgumentsField = value;
            }
        }
        
        /// <remarks/>
        public int serverErrorCode
        {
            get
            {
                return this.serverErrorCodeField;
            }
            set
            {
                this.serverErrorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string serverMessage
        {
            get
            {
                return this.serverMessageField;
            }
            set
            {
                this.serverMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string serverStackTrace
        {
            get
            {
                return this.serverStackTraceField;
            }
            set
            {
                this.serverStackTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://entity.openapi.registry.flashline.com")]
    public partial class AuditMsg
    {
        
        private long idField;
        
        private long auditIDField;
        
        private long createdByField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private string messageField;
        
        private int severityField;
        
        private string summaryField;
        
        private string[] summaryArgsField;
        
        private int summaryIDField;
        
        private int typeField;
        
        /// <remarks/>
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long auditID
        {
            get
            {
                return this.auditIDField;
            }
            set
            {
                this.auditIDField = value;
            }
        }
        
        /// <remarks/>
        public long createdBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> createdDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] summaryArgs
        {
            get
            {
                return this.summaryArgsField;
            }
            set
            {
                this.summaryArgsField = value;
            }
        }
        
        /// <remarks/>
        public int summaryID
        {
            get
            {
                return this.summaryIDField;
            }
            set
            {
                this.summaryIDField = value;
            }
        }
        
        /// <remarks/>
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://entity.openapi.registry.flashline.com")]
    public partial class ImpExpJob
    {
        
        private long idField;
        
        private AuditMsg auditMsgField;
        
        private string descField;
        
        private string displayNameField;
        
        private string errorMsgField;
        
        private int numCompleteField;
        
        private int numTotalField;
        
        private string resultStatusField;
        
        private System.Nullable<System.DateTime> startTimeField;
        
        private string stateField;
        
        private int typeField;
        
        private System.Nullable<System.DateTime> updateTimeField;
        
        private System.Nullable<System.DateTime> updatedDateField;
        
        private long userIDField;
        
        /// <remarks/>
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public AuditMsg auditMsg
        {
            get
            {
                return this.auditMsgField;
            }
            set
            {
                this.auditMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public int numComplete
        {
            get
            {
                return this.numCompleteField;
            }
            set
            {
                this.numCompleteField = value;
            }
        }
        
        /// <remarks/>
        public int numTotal
        {
            get
            {
                return this.numTotalField;
            }
            set
            {
                this.numTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string resultStatus
        {
            get
            {
                return this.resultStatusField;
            }
            set
            {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> updateTime
        {
            get
            {
                return this.updateTimeField;
            }
            set
            {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> updatedDate
        {
            get
            {
                return this.updatedDateField;
            }
            set
            {
                this.updatedDateField = value;
            }
        }
        
        /// <remarks/>
        public long userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://entity.openapi.registry.flashline.com")]
    public partial class AssetSummary
    {
        
        private long idField;
        
        private string uUIDField;
        
        private string longNameField;
        
        private string nameField;
        
        private long typeIDField;
        
        private string versionField;
        
        /// <remarks/>
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string longName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public long typeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://entity.openapi.registry.flashline.com")]
    public partial class KeyValuePair
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://entity.openapi.registry.flashline.com")]
    public partial class Categorization
    {
        
        private long idField;
        
        private int activeStatusField;
        
        private bool deletedField;
        
        private string displayNameField;
        
        private long levelField;
        
        private string nameField;
        
        private string recursiveNameField;
        
        private Categorization superField;
        
        private long typeIDField;
        
        private System.Nullable<System.DateTime> updatedDateField;
        
        /// <remarks/>
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int activeStatus
        {
            get
            {
                return this.activeStatusField;
            }
            set
            {
                this.activeStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool deleted
        {
            get
            {
                return this.deletedField;
            }
            set
            {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public long level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recursiveName
        {
            get
            {
                return this.recursiveNameField;
            }
            set
            {
                this.recursiveNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Categorization super
        {
            get
            {
                return this.superField;
            }
            set
            {
                this.superField = value;
            }
        }
        
        /// <remarks/>
        public long typeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> updatedDate
        {
            get
            {
                return this.updatedDateField;
            }
            set
            {
                this.updatedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(DateRangeSearchTerm))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TabStatusSearchTerm))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPNOTIN))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPNEQ))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPLTE))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPLT))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPLIKE))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPIN))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPGTE))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPGT))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPEQIC))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPEQ))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OPBTW))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class SearchTerm
    {
        
        private string keyField;
        
        private string operatorField;
        
        private string qualifierField;
        
        private string valueField;
        
        private string valueTypeField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string @operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string valueType
        {
            get
            {
                return this.valueTypeField;
            }
            set
            {
                this.valueTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TabStatusSearchTerm))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class DateRangeSearchTerm : SearchTerm
    {
        
        private string beginDateField;
        
        private string beginOperatorField;
        
        private string dateFieldField;
        
        private string dateFormatField;
        
        private string endDateField;
        
        private string endOperatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string beginDate
        {
            get
            {
                return this.beginDateField;
            }
            set
            {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string beginOperator
        {
            get
            {
                return this.beginOperatorField;
            }
            set
            {
                this.beginOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dateField
        {
            get
            {
                return this.dateFieldField;
            }
            set
            {
                this.dateFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dateFormat
        {
            get
            {
                return this.dateFormatField;
            }
            set
            {
                this.dateFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endOperator
        {
            get
            {
                return this.endOperatorField;
            }
            set
            {
                this.endOperatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class TabStatusSearchTerm : DateRangeSearchTerm
    {
        
        private bool approvedField;
        
        private long[] tabIDsField;
        
        private string[] tabNamesField;
        
        /// <remarks/>
        public bool approved
        {
            get
            {
                return this.approvedField;
            }
            set
            {
                this.approvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public long[] tabIDs
        {
            get
            {
                return this.tabIDsField;
            }
            set
            {
                this.tabIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] tabNames
        {
            get
            {
                return this.tabNamesField;
            }
            set
            {
                this.tabNamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPNOTIN : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPNEQ : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPLTE : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPLT : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPLIKE : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPIN : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPGTE : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPGT : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPEQIC : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPEQ : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class OPBTW : SearchTerm
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SFIDCandidateCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Or))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(And))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MetadataEntryCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MetadataEntryTypeCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SFIDCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(VendorCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RelationshipTypeCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RoleCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(UserCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SystemSettingsCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AssetTypeCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AcceptableValueListCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(DepartmentCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ProjectCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContactCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CategorizationTypeCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AssetCriteria))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ArtifactStoreCriteria))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class SearchTermGroup
    {
        
        private string[] orderByField;
        
        private string qualifierField;
        
        private SearchTermGroup[] searchTermGroupsField;
        
        private SearchTerm[] searchTermsField;
        
        private string[] supportedKeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] orderBy
        {
            get
            {
                return this.orderByField;
            }
            set
            {
                this.orderByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public SearchTermGroup[] searchTermGroups
        {
            get
            {
                return this.searchTermGroupsField;
            }
            set
            {
                this.searchTermGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public SearchTerm[] searchTerms
        {
            get
            {
                return this.searchTermsField;
            }
            set
            {
                this.searchTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] supportedKeys
        {
            get
            {
                return this.supportedKeysField;
            }
            set
            {
                this.supportedKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class SFIDCandidateCriteria : SearchTermGroup
    {
        
        private string[] sFIDValueCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] SFIDValueCriteria
        {
            get
            {
                return this.sFIDValueCriteriaField;
            }
            set
            {
                this.sFIDValueCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class Or : SearchTermGroup
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class And : SearchTermGroup
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class MetadataEntryCriteria : SearchTermGroup
    {
        
        private KeyValuePair entityCriteriaField;
        
        private long entryTypeCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public KeyValuePair entityCriteria
        {
            get
            {
                return this.entityCriteriaField;
            }
            set
            {
                this.entityCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public long entryTypeCriteria
        {
            get
            {
                return this.entryTypeCriteriaField;
            }
            set
            {
                this.entryTypeCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class MetadataEntryTypeCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class SFIDCriteria : SearchTermGroup
    {
        
        private long assetIDCriteriaField;
        
        private long projectIDCriteriaField;
        
        private string valueCriteriaField;
        
        /// <remarks/>
        public long assetIDCriteria
        {
            get
            {
                return this.assetIDCriteriaField;
            }
            set
            {
                this.assetIDCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public long projectIDCriteria
        {
            get
            {
                return this.projectIDCriteriaField;
            }
            set
            {
                this.projectIDCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string valueCriteria
        {
            get
            {
                return this.valueCriteriaField;
            }
            set
            {
                this.valueCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class VendorCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class RelationshipTypeCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class RoleCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class UserCriteria : SearchTermGroup
    {
        
        private string deptCriteriaField;
        
        private string nameCriteriaField;
        
        private string roleCriteriaField;
        
        private string statusCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string deptCriteria
        {
            get
            {
                return this.deptCriteriaField;
            }
            set
            {
                this.deptCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string roleCriteria
        {
            get
            {
                return this.roleCriteriaField;
            }
            set
            {
                this.roleCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusCriteria
        {
            get
            {
                return this.statusCriteriaField;
            }
            set
            {
                this.statusCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class SystemSettingsCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        private string sectionCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sectionCriteria
        {
            get
            {
                return this.sectionCriteriaField;
            }
            set
            {
                this.sectionCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class AssetTypeCriteria : SearchTermGroup
    {
        
        private string archeTypeCriteriaField;
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string archeTypeCriteria
        {
            get
            {
                return this.archeTypeCriteriaField;
            }
            set
            {
                this.archeTypeCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class AcceptableValueListCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class DepartmentCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class ProjectCriteria : SearchTermGroup
    {
        
        private string categorizationCriteriaField;
        
        private string departmentCriteriaField;
        
        private string exactMatchCriteriaField;
        
        private string nameCriteriaField;
        
        private string statusCriteriaField;
        
        private long userCriteriaField;
        
        private long userHasCriteriaField;
        
        private long userLeadByCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string categorizationCriteria
        {
            get
            {
                return this.categorizationCriteriaField;
            }
            set
            {
                this.categorizationCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string departmentCriteria
        {
            get
            {
                return this.departmentCriteriaField;
            }
            set
            {
                this.departmentCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string exactMatchCriteria
        {
            get
            {
                return this.exactMatchCriteriaField;
            }
            set
            {
                this.exactMatchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusCriteria
        {
            get
            {
                return this.statusCriteriaField;
            }
            set
            {
                this.statusCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public long userCriteria
        {
            get
            {
                return this.userCriteriaField;
            }
            set
            {
                this.userCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public long userHasCriteria
        {
            get
            {
                return this.userHasCriteriaField;
            }
            set
            {
                this.userHasCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public long userLeadByCriteria
        {
            get
            {
                return this.userLeadByCriteriaField;
            }
            set
            {
                this.userLeadByCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class ContactCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class CategorizationTypeCriteria : SearchTermGroup
    {
        
        private string nameCriteriaField;
        
        private string projectAssignCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string projectAssignCriteria
        {
            get
            {
                return this.projectAssignCriteriaField;
            }
            set
            {
                this.projectAssignCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class AssetCriteria : SearchTermGroup
    {
        
        private long iDCriteriaField;
        
        private string[] sFIDCriteriaField;
        
        private string uUIDCriteriaField;
        
        private long assetTypeCriteriaField;
        
        private string browsableOnlyCriteriaField;
        
        private Categorization categorizationCriteriaField;
        
        private string descriptionCriteriaField;
        
        private string exactMatchCriteriaField;
        
        private string generalCriteriaField;
        
        private string keywordCriteriaField;
        
        private string nameCriteriaField;
        
        private string uniqueElementCriteriaField;
        
        private string versionCriteriaField;
        
        /// <remarks/>
        public long IDCriteria
        {
            get
            {
                return this.iDCriteriaField;
            }
            set
            {
                this.iDCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] SFIDCriteria
        {
            get
            {
                return this.sFIDCriteriaField;
            }
            set
            {
                this.sFIDCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string UUIDCriteria
        {
            get
            {
                return this.uUIDCriteriaField;
            }
            set
            {
                this.uUIDCriteriaField = value;
            }
        }
        
        /// <remarks/>
        public long assetTypeCriteria
        {
            get
            {
                return this.assetTypeCriteriaField;
            }
            set
            {
                this.assetTypeCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string browsableOnlyCriteria
        {
            get
            {
                return this.browsableOnlyCriteriaField;
            }
            set
            {
                this.browsableOnlyCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Categorization categorizationCriteria
        {
            get
            {
                return this.categorizationCriteriaField;
            }
            set
            {
                this.categorizationCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descriptionCriteria
        {
            get
            {
                return this.descriptionCriteriaField;
            }
            set
            {
                this.descriptionCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string exactMatchCriteria
        {
            get
            {
                return this.exactMatchCriteriaField;
            }
            set
            {
                this.exactMatchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string generalCriteria
        {
            get
            {
                return this.generalCriteriaField;
            }
            set
            {
                this.generalCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string keywordCriteria
        {
            get
            {
                return this.keywordCriteriaField;
            }
            set
            {
                this.keywordCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nameCriteria
        {
            get
            {
                return this.nameCriteriaField;
            }
            set
            {
                this.nameCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uniqueElementCriteria
        {
            get
            {
                return this.uniqueElementCriteriaField;
            }
            set
            {
                this.uniqueElementCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string versionCriteria
        {
            get
            {
                return this.versionCriteriaField;
            }
            set
            {
                this.versionCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://query.openapi.registry.flashline.com")]
    public partial class ArtifactStoreCriteria : SearchTermGroup
    {
        
        private string basepathCriteriaField;
        
        private string downloadBasepathCriteriaField;
        
        private string hostCriteriaField;
        
        private string typeCriteriaField;
        
        private string versionSpecifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string basepathCriteria
        {
            get
            {
                return this.basepathCriteriaField;
            }
            set
            {
                this.basepathCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string downloadBasepathCriteria
        {
            get
            {
                return this.downloadBasepathCriteriaField;
            }
            set
            {
                this.downloadBasepathCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hostCriteria
        {
            get
            {
                return this.hostCriteriaField;
            }
            set
            {
                this.hostCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string typeCriteria
        {
            get
            {
                return this.typeCriteriaField;
            }
            set
            {
                this.typeCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string versionSpecifier
        {
            get
            {
                return this.versionSpecifierField;
            }
            set
            {
                this.versionSpecifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://entity.openapi.registry.flashline.com")]
    public partial class AuthToken
    {
        
        private string applicationTokenField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string applicationToken
        {
            get
            {
                return this.applicationTokenField;
            }
            set
            {
                this.applicationTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://base.openapi.registry.flashline.com")]
    public partial class ImportExportException : OpenAPIException
    {
        
        private ImpExpJob jobField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ImpExpJob job
        {
            get
            {
                return this.jobField;
            }
            set
            {
                this.jobField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://base.openapi.registry.flashline.com")]
    public partial class APIValidationException : OpenAPIException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://base.openapi.registry.flashline.com")]
    public partial class ImportExportCanceledException : OpenAPIException
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.openapi.registry.flashline.com/v300", ConfigurationName="OerProd.FlashlineRegistry")]
    public interface FlashlineRegistry
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OerProd.OpenAPIException), Action="", Name="OpenAPIException", Namespace="http://base.openapi.registry.flashline.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AssetSummary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTerm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTermGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="assetQuerySummaryReturn")]
        System.Threading.Tasks.Task<OerProd.AssetSummary[]> assetQuerySummaryAsync(OerProd.AuthToken pAuthtoken, OerProd.AssetCriteria pCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OerProd.OpenAPIException), Action="", Name="OpenAPIException", Namespace="http://base.openapi.registry.flashline.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AssetSummary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTerm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTermGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="authTokenCreateReturn")]
        System.Threading.Tasks.Task<OerProd.AuthToken> authTokenCreateAsync(string userName, string credential);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OerProd.OpenAPIException), Action="", Name="OpenAPIException", Namespace="http://base.openapi.registry.flashline.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AssetSummary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTerm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTermGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="assetReadXmlReturn")]
        System.Threading.Tasks.Task<string> assetReadXmlAsync(OerProd.AuthToken pAuthToken, long pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(OerProd.OpenAPIException), Action="", Name="OpenAPIException", Namespace="http://base.openapi.registry.flashline.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AssetSummary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTerm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchTermGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="assetQueryCountReturn")]
        System.Threading.Tasks.Task<int> assetQueryCountAsync(OerProd.AuthToken pAuthToken, OerProd.AssetCriteria pCriteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface FlashlineRegistryChannel : OerProd.FlashlineRegistry, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class FlashlineRegistryClient : System.ServiceModel.ClientBase<OerProd.FlashlineRegistry>, OerProd.FlashlineRegistry
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FlashlineRegistryClient() : 
                base(FlashlineRegistryClient.GetDefaultBinding(), FlashlineRegistryClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FlashlineRegistry.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlashlineRegistryClient(EndpointConfiguration endpointConfiguration) : 
                base(FlashlineRegistryClient.GetBindingForEndpoint(endpointConfiguration), FlashlineRegistryClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlashlineRegistryClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FlashlineRegistryClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlashlineRegistryClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FlashlineRegistryClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlashlineRegistryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OerProd.AssetSummary[]> assetQuerySummaryAsync(OerProd.AuthToken pAuthtoken, OerProd.AssetCriteria pCriteria)
        {
            return base.Channel.assetQuerySummaryAsync(pAuthtoken, pCriteria);
        }
        
        public System.Threading.Tasks.Task<OerProd.AuthToken> authTokenCreateAsync(string userName, string credential)
        {
            return base.Channel.authTokenCreateAsync(userName, credential);
        }
        
        public System.Threading.Tasks.Task<string> assetReadXmlAsync(OerProd.AuthToken pAuthToken, long pId)
        {
            return base.Channel.assetReadXmlAsync(pAuthToken, pId);
        }
        
        public System.Threading.Tasks.Task<int> assetQueryCountAsync(OerProd.AuthToken pAuthToken, OerProd.AssetCriteria pCriteria)
        {
            return base.Channel.assetQueryCountAsync(pAuthToken, pCriteria);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FlashlineRegistry))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FlashlineRegistry))
            {
                return new System.ServiceModel.EndpointAddress("https://soacatalog-oci.dtvpan.com/oer/services/FlashlineRegistry");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FlashlineRegistryClient.GetBindingForEndpoint(EndpointConfiguration.FlashlineRegistry);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FlashlineRegistryClient.GetEndpointAddress(EndpointConfiguration.FlashlineRegistry);
        }
        
        public enum EndpointConfiguration
        {
            
            FlashlineRegistry,
        }
    }
}
